### PR TITLE
fix: allow components to not need ALL

### LINKED ISSUE #64: ECS: Argument of type 'Component<{}>' is not assignable to parameter of type 'RawQuery'
In `world.createQuery(...)` we should just be able to supply any number of components without wrapping them all in the `ALL` macro.

### PR DESCRIPTION
**Pull request by christopher-buss**
Resolves #64.

### CODE REVIEW

File: src/lib/ecs/world.ts [hunk 1]
```diff
@@ -191,7 +191,7 @@ export class World {
 	 */
 	public createQuery(
 		arg: RawQuery | AnyComponent | TagComponent,
-		...raw: Array<RawQuery>
+		...raw: Array<RawQuery | AnyComponent | TagComponent>
 	): Query {
```
Comment (RigidStudios) [inline src/lib/ecs/world.ts:195]: Confused, why the multiplicity in the first place? Can't you just do the following?
```ts
public createQuery(
    ...raw: Array<RawQuery | AnyComponent | TagComponent>
): Query {
```

**Review by RigidStudios — CHANGES_REQUESTED** [review]

File: src/lib/ecs/world.ts (hunk 1 above)
Comment (christopher-buss) [reply src/lib/ecs/world.ts:195]: It's to force a single value. Because of the ... this could currently allow no values which would error.

**Review by RigidStudios — APPROVED** [review]
LGTM
